name: 機能追加・修正
description: 機能追加・修正はこちら
labels: [ "feature" ]
body:
  - type: textarea
    id: url_link
    attributes:
      label: URL
      description: Redmine,仕様書,QAのURLを記載してください
      placeholder: "- https://redmine.xxx.co.jp/issues/xxxxx"
  - type: textarea
    id: overview
    attributes:
      label: 概要
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 備考
