name: フォーム 技術的な改善・リファクタ
description: フォーム 技術的な改善・リファクタはこちら
labels: [ "refactor" ]
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: 背景・目的
    validations:
      required: false
  - type: textarea
    id: supplement
    attributes:
      label: 備考
