name: 不具合報告
description: 不具合報告はこちら
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 不具合の概要
      description: どのような不具合かを記載して下さい
      value: ""
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 発生環境
      description: どのような環境で発生するのか記載して下さい
      value: |
        端末:
        OS:
        アプリの種類:
        バージョン:
        API環境(本番/stg2):
    validations:
      required: false