name: 機能追加・修正
description: 機能追加・修正を行いたい時にはこちら
body:
  - type: input
    id: url_link
    attributes:
      label: URL
      description: 仕様書,QA,RedmineのURLを記載してください
      placeholder: ex. https://docs.google.com/~
  - type: textarea
    id: overview
    attributes:
      label: 概要
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 備考
