name: 機能要望
description: 機能追加・削除を行いたい時にはこちら
body:
  - type: input
    id: url_link
    attributes:
      label: URL
      description: 仕様書,QA,RedmineのURLを記載してください
      placeholder: ex. https://docs.google.com/~
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: このissueの概要を記載をしてください
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 備考
      description: 備考があれば記載してください。
      value: 特になし
