name: バグ報告
description: バグ報告はこちら
labels: ["bug"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        不具合の概要を記載してください。
        期待される結果などもあると良いです。
        見た目に関係する場合は、スクリーンショット等を貼り付けてください。
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 発生環境
      description: |
        発生環境を記載してください。
        以下の特定の条件で発生するならそれも記載してください。
        (特定の作品で発生するなら)作品名:
        (ログイン状態で発生するなら)citi_id:
      value: |
        端末:
        OS:
        アプリの種類:
        バージョン:
        API環境(本番/stg2):
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |
        1. 
        2. 
        3.
  - type: textarea
    id: supplement
    attributes:
      label: 備考
      description: 備考があれば記載してください。
      value: 特になし
  - type: input
    id: issue_template_version
    attributes:
      label: issue_template_version
      description: issueの検索などで利用状況を調べるためにあるので編集しないでください。
      value: bug_report_20240404